version: '3.0'

volumes:
  mongodbvol:

services:
  mongodb:
    container_name: mongodb
    build:
      context: .
      dockerfile: Dockerfile-mongodb
    image: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodbvol:/data/db

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    ports:
      - "8081:8081"
    links:
      - mongodb:mongodb